### ISSUE TITLE
Non-breaking spaces in BIE search queries greatly reduces search results

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/ala-bie-hub#107]
Non-breaking space characters can become included in species names and other data from outside sources, and this can cause unexpected behaviour when taken to the ALA. When included in BIE searches, this greatly reduces the search results, eliminating for example partial matches for genus or common name results, in data resource names or support articles, etc).

https://bie.ala.org.au/search?q=Sagittaria%C2%A0platyphylla
https://bie.ala.org.au/search?q=Sagittaria+platyphylla

Copy the following text for an example: Sagittaria platyphylla

**Comment by adam-collins** [comment]
Fixed in test.
