### ISSUE TITLE
AusTraits trait definitions update

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/ala-bie-hub#108]
I'm writing to let you know that the AusTraits API is ready for another update and I am hoping to complete this over the weekend - the traits tab might be down for 15 minutes or so while this occurs. 

No action is required on your end for the data update, however the AusTraits trait definitions are now located at a new location which means one of the links on the traits tab is currently broken. 
Its the link to the trait definitions just below the download csv button on the ALA species traits tab (https://traitecoevo.github.io/austraits.build/articles/trait_definitions.html) and needs to be replaced by this: [https://w3id.org/APD/index.html](https://w3id.org/APD/) .

Links to individual trait definitions in the categorical and numeric trait tables are also currently broken, but will be fixed in the new update.

**Comment by dcol2804** [comment]
A second issue that could be fixed at the same time is in the text referring to the number of traits, sourced from the API endpoint /trait-count (e.g. http://traitdata.austraits.cloud.edu.au/trait-count?taxon=Eucalyptus%20saligna). 

The test returned from the current API endpoint reads: 

There are 29 **traits** available for Eucalyptus saligna, with data for 38 further traits in the AusTraits database. These are accessible via the download CSV button or alternatively the entire database can be accessed at doi.org/10.5281/zenodo.3568417

But on the ALA traits tab (https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2912252#ausTraits)  it reads:

There are 29 available for Eucalyptus saligna with data for 57 further traits in the [AusTraits](https://austraits.org/) database. These are accessible via the download CSV button or alternatively the entire database can be accessed at https://doi.org/10.5281/zenodo.3568417

The word "traits" is missing. 

This also needs to be fixed

**Comment by adam-collins** [comment]
Using [https://w3id.org/APD/](https://w3id.org/APD/) because [https://w3id.org/APD/index.html](https://w3id.org/APD/index.html) is not working.

Fixed the missing `traits` 

pull request https://github.com/AtlasOfLivingAustralia/ala-bie-hub/pull/115
