### ISSUE TITLE
Overridden wikipedia URL is not used in the wikipedia link

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/ala-bie-hub#110]
fixed by https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/ae5c1c98c45a882d37abe2d751e7197246fba24e

**Comment by kylie-m** [comment]
can be tested at https://bie-test.ala.org.au/species/https:/biodiversity.org.au/afd/taxa/ecb004b3-7d41-402f-b159-0c8254b17a27. - this is working for me now
