### ISSUE TITLE
type specimen images api call excludes associated records

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/ala-bie-hub#120]
In this [BIE gallery for golden stag beetles](https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/59fede41-4359-40c9-bff7-c0cbcab02440#gallery), only 3 specimen images show up when 12 should.

The [BIE gallery API call for type specimen images](https://biocache.ala.org.au/occurrences/search?q=lsid:https://biodiversity.org.au/afd/taxa/59fede41-4359-40c9-bff7-c0cbcab02440&fq=multimedia:%22Image%22&pageSize=20&facet=off&start=0&fq=basis_of_record:PreservedSpecimen&fq=-type_status:*&im=true&fq=spatiallyValid:true&fq=-user_assertions:50001&fq=-user_assertions:50005&fq=-duplicate_status:ASSOCIATED&fq=-duplicateType:DIFFERENT_DATASET#tab_recordImages) attempts to apply the logic from the DQ filters (I think), that is:

* Exclude "Associated records"
* Exclude "DIFFERENT DATASET"
* Exclude Open/Unconfirmed User assertions
* Spatially valid

Looking at the results, only 3 type specimen images come back, when there should be 12. 
If we remove the "Exclude Associated records" filter, then all 12 appear.

<img width="717" alt="image" src="https://github.com/AtlasOfLivingAustralia/ala-bie-hub/assets/1271932/a4072657-74f8-47b7-b5f4-f4f52c883e00">

The clustering/duplicate algorithm is very likely to label specimen for the same species and collection as duplicates (was designed to, in fact). However, we only want to exclude the images if they are duplicates with a duplicateType of DIFFERENT_DATASET. 

Could the gallery be fixed to do this? 

Also, is the plural of specimen specimens? Or is it just specimen?

**Comment by adam-collins** [comment]
The required config change is in production.
