### ISSUE TITLE
Add UserAgent for BIE hub

### ISSUE THREAD

**Issue by joe-lipson** [AtlasOfLivingAustralia/ala-bie-hub#124]
Requests from BIE hub use the default Java UserAgent Java/11.0.24.

This needs to be changed so it identifies itself with the application and version like our other apps e.g. profile-hub/4.2.2

The default Java UA makes analysing traffic and creating rules and filters difficult.

![Image](https://github.com/user-attachments/assets/0c37f806-5be6-41e5-a8f1-4c33c0990fb3)

**Comment by nickdos** [comment]
See [change for alerts](https://github.com/AtlasOfLivingAustralia/alerts/commit/b1e867e1a5d3f3d0b48122f306a8476bba6ffca3)

**Comment by nickdos** [comment]
Tested locally and checked bie-test-ws access logs to confirm its working:

`172.30.1.246 - - [09/Dec/2024:12:41:46 +1100] "GET /ws/species/https://biodiversity.org.au/afd/taxa/7e6e134b-2bc7-43c4-b23a-6e3f420f57ad HTTP/1.1" 200 18800 "-" "ala-bie-hub/4.2.0-SNAPSHOT" "140.253.238.151" request_time=0.026 upstream_response_time=0.024 upstream_connect_time=0.000 upstream_header_time=0.024 upstream_cache_status=-`
