### ISSUE TITLE
Fix or work-around for misbehaving search page https://bie.ala.org.au/species/

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/ala-bie-hub#125]
A user's raised an issue with this particular search page on BIE: https://bie.ala.org.au/species/
For some reason it creates malformed searches that can never work: https://bie.ala.org.au/species/search?fq=idxtype%3ATAXON+OR+idxtype%3ACOMMON&q=osphranter
However, removing "species/" from the URL produces a search page and results that do work.
We've identified how users are finding it, it's the first Google result for "species search ala" so Google has found and cached it somewhere.
We should redirect this path back to the BIE homepage. We might be using a sitemap.xml for BIE too, and it might be listed there too.

**Comment by nickdos** [comment]
Fixed (on dev) with a single config change

![image](https://github.com/user-attachments/assets/5f9b6fcc-2d6d-4d19-bac8-017783719285)

Show Taxon not found, which makes sense as the path part after `/species/` usually contains the name or guid.

A better fix could be done later but this config change can be deployed quickly without needing CAB approval.

**Comment by nickdos** [comment]
Deployed to prod
