### ISSUE TITLE
Creation of unnecessary species pages

### ISSUE THREAD

**Issue by joe-lipson** [AtlasOfLivingAustralia/ala-bie-hub#130]
submitted by @CamSlatyer 

Species pages are being created for all synonyms in the ALA instead of preferred names only (accepted, inferredAccepted, unreviewed, and inferredUnplaced) names. These species pages are accessible and searchable in the form: https://bie.ala.org.au/species/Corbicula_fluminea where the name is expressed genus_species or genus_subgenus_species. Every synonym we have tested has one, which effectively doubles the number of species pages in the ALA. The synonym pages should be removed as they are misleading. Users also need to be directed to the current name page from a synonym name. For example : https://bie.ala.org.au/species/Macropus_rufus should send the user to https://bie.ala.org.au/species/Osphranter_rufus.

**Comment by kylie-m** [comment]
This is working for me. I've tested the following and they all redirect to the correct bie-test page:
- https://bie-test.ala.org.au/species/Macropus_rufus --> Osphranter rufus
- https://bie-test.ala.org.au/species/Corbicula_fluminea --> Corbicula (Corbicula) fluminea
- https://bie-test.ala.org.au/species/Macropus_major --> Macropus giganteus
- https://bie-test.ala.org.au/species/Hyla_aurea --> Litoria aurea
- https://bie-test.ala.org.au/species/Aseroe_pallida --> Aseroe rubra
- https://bie-test.ala.org.au/species/Eucalyptus_coriacea --> Eucalyptus pauciflora 

Also the standard bie-hub test cases all pass, see docs here on Teams:
https://csiroau.sharepoint.com/:x:/r/sites/AtlasofLivingAustraliaTeams/Shared%20Documents/Teams/Systems/Testing/BIE/bie-hub-4.1.2-testing-nov24.xlsx?d=w0b17e42aa6c9428b8d0473e18980e3ed&csf=1&web=1&e=2HCtbY
