### ISSUE TITLE
Missing links to Wikipedia articles from some BIE pages

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/ala-bie-hub#133]
Raised in https://support.ehelp.edu.au/a/tickets/219556

Species pages on BIE draw information from Wikipedia articles, and should include a link to the source Wikipedia article under each section, for example: https://bie.ala.org.au/species/https://id.biodiversity.org.au/taxon/apni/51286863#overview

However, a user has identified that some pages are missing these links - for example: https://bie.ala.org.au/species/NZOR-6-37743

The content for this page has clearly come from https://en.wikipedia.org/wiki/Ourisia_caespitosa but the citation link and relevant CC license information are missing.

It's unclear what the pattern is (given that the Acacia dealbata page is not affected) but working up the classification tree, the Wikipedia data for Charophyta is also missing citations: https://bie.ala.org.au/species/https://id.biodiversity.org.au/taxon/apni/51744351#overview

As is Plantae, the top level for plants: https://bie.ala.org.au/species/https://id.biodiversity.org.au/taxon/apni/51744352#overview

I'll add further examples if/as they come to light.

**Comment by timhicks-ala** [comment]
Two more examples, from family and genus level:
https://bie.ala.org.au/species/https%3A//id.biodiversity.org.au/taxon/apni/51702961
https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2920381

**Comment by timhicks-ala** [comment]
One more example of missing Wikipedia links on a species-level page: https://bie.ala.org.au/species/NZOR-6-49224

**Comment by nickdos** [comment]
Hi @timhicks-ala - fix is deployed to [bie-test](https://bie-test.ala.org.au/).

E.g. https://bie-test.ala.org.au/species/https://id.biodiversity.org.au/taxon/apni/51744351

Please test a few of those pages, when you get a chance, next week (no rush).

**Comment by timhicks-ala** [comment]
Hi @nickdos - all reported cases appear to be fixed in test.

**Comment by kylie-m** [comment]
Thanks @nickdos , 

Have done a quick check on several bie-test pages at various taxonomic levels - all are showing the Wikipedia link for me.

I've also done a quick round of functional testing as per the testing docs (https://confluence.csiro.au/display/ALASD/ALA-BIE+Manual+%28Sanity%29+testing) - for checking BIE page content on each tab - all passing

**Comment by nickdos** [comment]
Deployed to prod - @timhicks-ala you can let the reporting user know it fixed now.
