### ISSUE TITLE
Popup survey (or link to survey)

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/ala-bie-hub#15]
Looking to create a popup notification for users on the BIE species pages for a set time (such as a few weeks) to link to this survey: https://www.surveymonkey.com/r/VHX23C2 (final wording approval still TBA, but basic structure and idea is there)

This is part of the bigger BIE species info page UX project work, to gain insight into what content users find useful on these pages. 

There is an option to create pop-ups using Survey Monkey (SM generates code to embed) but they're not very customisable or on-brand for ALA. This is the closest I've been able to achieve using Survey Monkey:
![Screen Shot 2022-09-19 at 5 01 22 pm](https://user-images.githubusercontent.com/90439797/190965494-dc83c784-a1e0-49e5-9dd5-fd6c2093b936.png)

I'd like to be able to add something simpler such the Bootstrap modal below:
(text reads: As part of the ALA’s continual improvement process, we’d appreciate your help to complete ALA’s species page survey. Results will be used to improve our species pages for our users. ALA will not collect any personal information for the purposes of this survey, and survey results will not be published or made available to external parties. For any questions, please contact support@ala.org.au.)

![BIE-survey-popup](https://user-images.githubusercontent.com/90439797/199129160-8b80a739-d215-4f3b-8150-a3ec92b4c85c.png)

**Comment by javier-molina** [comment]
How about adding a sentence letting users know how long the survey is going to take so they don't jump blindly to a 40-questions survey and then give up half way through?

I would also add a More/less accordion (hidden by default) with the last two paragraphs in order of keeping things simple for users.

"

> This survey consist of x questions and will take y minutes. Your feedback will allow us to improve our species pages.
> 
> View more >
> 
> As part of ALA's continual improvement process we'd appreciate your help to complete this ALA's species page survey.
> 
> ALA will not collect any personal information in this survey. Survey results will not be published or made available to external parties. See our [Privacy Policy](https://www.ala.org.au/terms-of-use/privacy-policy/) for more details. 
> 
> For any questions, please contact support@ala.org.au

"

**Comment by sughics** [comment]
Closing issue as the survey has been released with [v2.1.0](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/releases/tag/2.1.0)
