### ISSUE TITLE
Lists content not appearing on BIE

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/ala-bie-hub#16]
In BIE content is usually served from the lists tool
- In the right hand side column, if that species name appears in a list in the list tool marked `include in species pages` then a box appears containing data from that list, with the list title appearing as a header on the box. This is not happening currently.
- the conservation statuses are usually displayed on the left hand side in a `conservation status` box. EPBC is not appearing in this example https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/31869a0e-2ce5-40be-b6f6-c0231a48b414 when it clearly appears in the EPBC list https://lists.ala.org.au/speciesListItem/list/dr656?q=Anthochaera (lmk if this is a data issue)

The distribution map (blue) placement looks terrible.

**Comment by adam-collins** [comment]
Both issues are specieslist-webapp.
1. These items are not included because the path variable LSID was not handling LSIDs containing `//`
2. These items are not imported because `ws/speciesListItems` now has a limit on the max number joined records due to the api gateway. The default is `max=400`. Two issues are the paging is missing from the `bie-index` call and the paging is based on the join resulting in overlapping pages that require merging.

Pipelines and biocache-service also need paging implemented for the changed webservice behaviour.

**Comment by adam-collins** [comment]
1. `\\` handling https://github.com/AtlasOfLivingAustralia/specieslist-webapp/commit/0882c5b7056208661dd433c0b97a90501ca968fc
2. fix webservice paging https://github.com/AtlasOfLivingAustralia/specieslist-webapp/commit/c9634d8389fb181c9ea832723df5d26f5b332f23
3. add paging to speciesListItems call https://github.com/AtlasOfLivingAustralia/bie-index/pull/359
4. add paging to speciesListItems call https://github.com/AtlasOfLivingAustralia/spatial-service/commit/a990a72698d360a1bad34ffb9d16aaeda03f507e
5. add paging to speciesListItems call https://github.com/AtlasOfLivingAustralia/biocache-service/tree/species-list-items-paging

Pipelines uses a different webservice to get this information from lists and does not need a change.

**Comment by adam-collins** [comment]
lists-test and bie-test are running with the fixed code and BIE SOLR index. https://bie-test.ala.org.au/species/https://biodiversity.org.au/afd/taxa/31869a0e-2ce5-40be-b6f6-c0231a48b414 (ignore images-test javascript errors)

**Comment by adam-collins** [comment]
5. ala-install change https://github.com/AtlasOfLivingAustralia/ala-install/commit/03124a9b80320735b528f402f98688f7207a6f95

**Comment by sat01a** [comment]
Thanks @adam-collins for following this through, sushant will review and incorporate this changes and release for internal testing. ccing: @sughics @kylie-m @peggynewman @elywallis

**Comment by peggynewman** [comment]
The Conservation Status issue seems to have been resolved, hooray!

But I'm consistently getting an error that I have to click multiple times to get rid of when I go to a BIE page:

![Image](https://user-images.githubusercontent.com/1271932/199888901-1605430c-ddd6-4d58-ae82-d1476c2a77ea.png)

But there are still some problems:
[Anthochaera (Xanthomyza) phrygia](https://bie-test.ala.org.au/species/https://biodiversity.org.au/afd/taxa/31869a0e-2ce5-40be-b6f6-c0231a48b414) - Regent Honeyeater 
List boxes are showing up but the EOL text feed isn't

In the ones I look at, the Datasets box sentence is missing a count, ie, it says `datasets have provided data to the Atlas of Living Australia for this species.` but there should be a number in front.

[Gymnobelideus leadbeateri](https://bie-test.ala.org.au/species/https://biodiversity.org.au/afd/taxa/6119c642-08ad-403e-b8c9-215814f63ee3) - Leadbeater's Possum is working, except for this problem.

**Comment by sughics** [comment]
@peggynewman  the errors you are seeing - I'm pretty sure thats related to the content type returned by biocache-service - https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/17 - I currently implementing a fix

**Comment by sat01a** [comment]
Fixed and Deployed
