### ISSUE TITLE
Admin function to set preferred image not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-bie-hub#23]
There should be a star icon on the image popup modal (for users with ROLE_ADMIN), when you click on an image thumbnail on the gallery view. This is no longer appearing (I checked I was logged in with the correct account that has ROLE_ADMIN).

![image](https://user-images.githubusercontent.com/532845/138628784-895cec14-5f75-4507-8c2b-672bc7feccea.png)

- [ ] Fix the set preferred image button (star)

The code for this is (probably) in the [`images-client-plugin`](https://github.com/AtlasOfLivingAustralia/images-client-plugin) that handles the viewing of images. The bug is likely **just a case of some missing config** vars for the BIE front end. @patkyn wrote the original code, so if unclear, ask her for guidance.

Update: docs on config vars: https://github.com/AtlasOfLivingAustralia/images-client-plugin#configuration

**Comment by nickdos** [comment]
Looking at config vars set in BIE production, it seems they have the required vars ([according to the doco](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/23#:~:text=https%3A//github.com/AtlasOfLivingAustralia/images%2Dclient%2Dplugin%23configuration) anyway):

config var | value
-- | --
speciesList.preferredListName | ALA Preferred Species Images
speciesList.preferredSpeciesListDruid | dr4778
allowedImageEditingRoles | ROLE_ADMIN,ROLE_EDITOR

**Comment by sughics** [comment]
Issue not longer exists in current build and deployments of ala-bie-hub. Confirmed with @nickdos . 
Clearing browser cache recommended if this issue is encoutered.

**Comment by nickdos** [comment]
Was not clearing cache (I lied) but using incognito mode. @timhicks-ala confirms the same thing. I think we should raise a new issue or reopen this one.
