### ISSUE TITLE
AusTraits Enhancements

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/ala-bie-hub#26]
- Mobile Responsiveness (Along with other BIE content?)
- Reposition **How to cite AusTraits data** to a more prominent location in the tab. (e.g. In a column Next to the AusTraits title and image)
- Request AusTraits to also include doi link with `/trait-count` api response. 
- Test with HTTPS version with AusTraits API (when released)
- Only render a trits table when the data is available - currently table header is still displayed when no trait data is available.

**Comment by adam-collins** [comment]
- More details required for `Mobile Responsiveness`
- https://github.com/AtlasOfLivingAustralia/ala-bie-hub/pull/38
- `/trait-count` api is already in use.
- HTTPS not yet available.
- When no data is available `No records found` is display instead of the table.

**Comment by adam-collins** [comment]
Moving unresolved items to https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/41
