### ISSUE TITLE
BIE gallery shows "No images available for this taxon" before loading images on a slow connection

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/ala-bie-hub#31]
A user has reported that when opening a BIE gallery page, for example: https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/837706e8-b6d2-48f8-bd8b-97c87d46c83f#gallery

If the connection or system is slow at the time, it can show the message "No images available for this taxon" for some time before actually loading images. This messages is misleading and incorrect in this case.

The suggested feature is to detect when a gallery actually does have images, and instead show "Loading images..." or similar instead of "No images available". This lets the user know to expect images to load, if slowly, rather than assuming there are none available.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/9c8681b835ba034838047083cf6d0062ecad731f
