### ISSUE TITLE
Separate from EOL,pull content directly from Wikipedia

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#42]
As a user of the ALA I want to see species descriptions from Wikipedia so I can get a detailed overview of the species I have sought, for personal interest/research. 

**Background**
Currently BIE species descriptions are sourced from [Encyclopaedia of Life](https://eol.org/) (EOL) which in turn sources that information from Wikipedia.

EOL is no longer maintained which results in incomplete and inaccurate descriptions been displayed in BIE species pages.

**Requirements**
Source species descriptions directly from Wikipedia and decommission current feed from EOL.

**Constraints**
Finding descriptions for species is not as simple as issuing an API call with a species name. Species names are ambiguous hence a more sophisticated matching algorithm needs to be developed using the species taxonomy tree.

The value EOL provided was that species matching process, iNaturalist already displays species descriptions from Wikipedia hence reaching out with the iNaturalist technical team will be a good first step.

Refer also to https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/255

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/27473435766bfc21fee1b42a2f4233544c844b23
