### ISSUE TITLE
Manual content blacklisting

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#43]
As an administrator for BIE I want to prevent species descriptions for particular species from displaying as they might be deemed inappropriate and threaten to damage ALA reputation.

**Background**
The ALA does not have control on the editorial process of the species descriptions where it sources information from (currently Wikipedia via EOL). In some instances the information sourced might be considered inaccurate, offending, related to a different species, for example Eucalyptus described as an invasive species from the point of view of a botanist in the USa.

TBC What is the current implementation?
It seems this is a regexp-like based configuration file maintained by a software developer.

**Requirements**
- A BIE administrator with no technical knowledge needs access to a UI function to block (blacklist) content  for a specific species.
- Updates to ALA's taxonomy must preserve the rules for existing blocked content.
- An additional admin screen must be created to display existing species pages which content has been blocked.

Related issue: #47

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/27473435766bfc21fee1b42a2f4233544c844b23
