### ISSUE TITLE
Remove sequences tab

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#45]
**Background**

Both internal and external feedback about the species pages has indicated a lack of engagement with the 'Sequences' tab in its current form. 'Sequences' tab content will be redesigned as part of the new Species Pages design. For the time being it provides more value to get rid of this tab.

**Requirements**

- Remove 'Sequences' tab from the species pages

**Considerations**
- We should alert users to this change before/after it happens. Inform users that they can still access sequences via GenBank externally?

**Comment by adam-collins** [comment]
In production (removed tab)
