### ISSUE TITLE
Manual hero image selection

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#46]
Draft

As an administrator for BIE, I want to select the first 5 images to be displayed for a species page so I can highlight images displaying different features for a species.

**Background**
Hero images on species page overviews can sometimes display poor quality, low resolution, poorly shot, misidentified, and/ or inappropriate images of species.

Hero images are the first set of images a user will be able to see upon entry to the species pages. It is important that these are accurate, high quality, and representative, particularly for highly visited/recorded species.

Unless it is possible to reliably automate a selection of consistently high quality hero images for each species, it is recommended that we use manual curation to achieve this outcome. As manual curation of all ALA species is a big undertaking, it is also recommended that this process starts with the first 200 most highly visited species pages according to fathom/google analytics for greater impact on user experience short-term.

**Requirements**
- As a BIE administrator, using the gallery tab, I will have controls to select the image preference (1 to 5)

**Constraints**
Relevant issue. Admin function to set preferred image not working. https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/23 

**Additional information**
BIE Administrators should use [this guide](https://confluence.csiro.au/display/ALASD/Image+Curation+for+ID+Characters) when picking representative images

**Comment by javier-molina** [comment]
Duplicated images issue has been captured here #50

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/3be715e31116cd83e1e5cb793ef9d06a82fda1f5
