### ISSUE TITLE
Manually re-map species

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#47]
As an administrator for BIE, I want to manually override the mapping from a species in the ALA to the content sourced from wikipedia so I can fix incorrect matches.

**Background**
The algorithm that matches species to description content is not perfect and sometimes it will point to the wrong content. TBC Changes in ALA taxonomy can change this mapping?

**Requirements**

- A BIE administrator with no technical knowledge needs access a UI function to manually map a species to the specific source for content descriptions.
- Updates to ALA's taxonomy must preserve the rules for manual mapping.
- An additional admin screen must be created to display existing manual mappings.

Related AtlasOfLivingAustralia/ala-bie-hub#43

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/27473435766bfc21fee1b42a2f4233544c844b23

**Comment by aliciadoddy** [comment]
Hi @adam-collins 
Demoed with Kylie and the ability to change wiki url seems logical, easy to use, and looks to be functioning well, however I think there still needs to be plans around an admin screen, or at least some kind of viewable log to keep a trail of, and oversee decisions made around, the manual mappings made by admins. This applies to issues #43 as well 

Cheers
