### ISSUE TITLE
Manual  image flagging and deprioritisation

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#49]
Draft

As an administrator for BIE, I want to flag images that might be contentious or unseemly so they can be filtered out by default in the hero images and gallery view.

**Background**
Some species pages have an overrepresentation of images that could be perceived as contentious, uncomfortable, or confronting, such as roadkills. While there may be genuine reasons to continue to provide access to those pictures, by default these images are unsuitable to be the first to be displayed in the image gallery or hero images. It would be ideal for users to be able to choose whether they see these images or not.

**Requirements**

- A BIE administrator, using the gallery view, must be able to flag an image as "content warning"
- By default flagged images will be hidden but there must be a control in the UI to disable that filter.
- 'Content warning' images will have a tag displayed as an overlay.
- Flagged images are not available to be set as hero image.

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/3be715e31116cd83e1e5cb793ef9d06a82fda1f5
