### ISSUE TITLE
Link to spatial portal

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#51]
**Background**

Internal and external feedback has indicated the text on the button underneath the species page occurrence map, 'View interactive map' is a bit unclear to users. There are multiple interactive maps on the ALA website, including the occurrence map the users would already by viewing on the page. It is not obvious that this button would take users to the spatial portal specifically.

Refer also to https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/259 

**Requirements**

- Rename 'View interactive map' text on this button to 'View interactive map in the Spatial Portal'

**Comment by kylie-m** [comment]
This is looking great; is it possible to wrap the text for smaller screens?

**Comment by adam-collins** [comment]
In production (without wrapping) Wrapping is in milestone 3.1.0
