### ISSUE TITLE
Link to occurrence records

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#52]
**Background**

Internal and external feedback has indicated the text on the button underneath the species page occurrence map, 'View records' is a bit unclear to users. It would be helpful for improving user navigation around the site if this button text offered more information.

 Refer also to https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/259 

**Requirements**

-Rename 'View records' button text to 'View and download occurrence records'

**Comment by kylie-m** [comment]
This is also looking great; is it possible to wrap the text for smaller screens?

**Comment by aliciadoddy** [comment]
Same comment as above, shrinking the browser length-ways seems to cut off the text. Is wrapping the text possible?

**Comment by adam-collins** [comment]
On production (without wrapping). Wrapping is in milestone 3.1.0
