### ISSUE TITLE
Order synonyms by date

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#53]
**Background**
Within the 'synonym' section of the 'Names and sources' table within the 'Names' tab on the species pages, synonyms do not appear to be listed in any obvious or coherent order.

These synonyms provide a traceable history of published names for a given species. It would be sensical for these names to appear in chronological order.

See example, _Marsia japonica_, https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/9237f367-d84e-4ca3-ba45-2ac958174afb#names

**Requirements**
- Order synonyms within the Names tab in chronological order by year of publication, starting with most recent year.

**Comment by adam-collins** [comment]
In production.
