### ISSUE TITLE
Remove outdated/broken links at bottom of pages (PESI,ARKive,EOL)

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#54]
**Background**

The 'online resources' section of the species page overview has several non-useful, and/or non-functional links. GBIF and BHL are still well-maintained external sites that are worth linking to, but PESI, Arkive, and EOL are not. Additionally, the inclusion of JSON in this grouping is unsuitable.

Refer also to https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/32

**Requirements**
- Remove PESI, ARKive, and EOL from online resources
- Move Json to API icon in top right corner similar to the one in Biocache

![Image](https://github.com/AtlasOfLivingAustralia/ux-ui/assets/118698799/5c98d700-4663-49bd-aaf6-f4c7c2ffae6c)

![Image](https://github.com/AtlasOfLivingAustralia/ux-ui/assets/8326394/1b6d7661-8bbe-4585-aab8-909c7ad533d4)

**Comment by sughics** [comment]
@adam-collins  - looks like we still need to update the "JSON" button  for this requirement ? 
Moving this requirement to 3.1.1 milestone.

> Move Json to API icon in top right corner similar to the one in Biocache

**Comment by adam-collins** [comment]
In Production.
