### ISSUE TITLE
Add/display map scale

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#57]
**Background**

Currently the species page occurrence map is missing a scale. This is a key, basic map element that has been missing for years. It should be added.

**Requirements**

- Add scale to species page occurrence map display.
- Scale should be appropriately placed and sized so as not to obstruct occurrence records or other map elements. 
- It should be placed in the bottom right corner and actively adjust with the zoom function.
- It should be big enough to make out the unit values easily, without being distractingly large.

Refer to iNaturalist map for example https://www.inaturalist.org/taxa/42983-Phascolarctos-cinereus

Refer also to https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/223

**Comment by adam-collins** [comment]
In production
