### ISSUE TITLE
Move Json to API icon in top right corner similar to the one in Biocache

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/ala-bie-hub#62]
Update the icon and working to be similar to biocache. 

Original Issue - https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/54

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/1e50371da5c5ef96afdcec0eef94352f9c90456c
