### ISSUE TITLE
Create link to Trove in 'Online resources' section

### ISSUE THREAD

**Issue by aliciadoddy** [AtlasOfLivingAustralia/ala-bie-hub#67]
**Background** 
Trove is no longer considered suitable to occupy the literature tab. However, Trove is a good source of free literature, presented without paywall. This would likely still prove useful to users looking for certain literature. As such, it would be ideal to still include Trove on the species pages, but in the form of a link to the external site located in the ‘online resources’ section.

**Action**

- Add link to Trove within 'Online resources' section of the species pages.

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/61d2c997769f6ef6e02ab3b747b1fdacd960c3e2
