### ISSUE TITLE
Order data partner information by descending number of records

### ISSUE THREAD

**Issue by aliciadoddy** [AtlasOfLivingAustralia/ala-bie-hub#68]
**Background**

Within the data partners tab of the species pages, the table does not appear to have a clear or consistent order. The table does not appear to be sorted alphabetically according to datasets, nor by license, nor by record number. Unclear what the current order is.

see

https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/fungi/60095717#data-partners

https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/e9d6fbbd-1505-4073-990a-dc66c930dad6#data-partners

It would be ideal to sort this information consistently by descending number of records.

**Action**

- Sort tabulated information in data partners tab by descending number of records.

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/5546bc53770500a8db4d76d777fb9e7f8432a575
