### ISSUE TITLE
Integration of ALA with AusTraits

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/ala-bie-hub#7]
Integration of ALA with AusTraits

https://confluence.csiro.au/display/ALASD/50+-+AusTraits 
https://confluence.csiro.au/display/ALASD/Notes+from+AusTraits+meetings 

Ansible Changes
 - https://github.com/AtlasOfLivingAustralia/ansible-inventories/tree/aus-traits
  - https://github.com/AtlasOfLivingAustralia/ala-install/tree/aus-traits

**Comment by kylie-m** [comment]
Test cases:

- [ ] How page performs if the AusTraits server is down

- [ ] What if table rows > 100-200

- [ ] How pages without trait data will appear

**Comment by sughics** [comment]
Pending next(prod) release of AusTraits and additional changes to the AusTraits API before further dev work.
