### ISSUE TITLE
Bug fix - system trying to read an image file as an audio recording, causing audio recording error for some species pages.

### ISSUE THREAD

**Issue by aliciadoddy** [AtlasOfLivingAustralia/ala-bie-hub#71]
Example https://bie.ala.org.au/species/https:/biodiversity.org.au/afd/taxa/2a4e373b-913a-4e2a-a53f-74828f6dae7e#overview

![Image](https://user-images.githubusercontent.com/118698799/257407992-842c3dbd-91c2-4f96-8c0e-1ebe29c48eec.PNG)

See also observation record for audio
https://biocache.ala.org.au/occurrence/c484e77a-6460-4d9f-b92b-54956a5ed752

![Image](https://user-images.githubusercontent.com/118698799/257408120-bf91b519-60d9-473e-af36-6d79e0b8ace0.PNG)

![Image](https://user-images.githubusercontent.com/118698799/257408172-a47c25c0-5c2f-4086-9dce-18bf58f73ac5.PNG)

It appears the system is also trying to read audio as an image, as well as attempting to read the images attached to the same record as audio. 

Investigate cause and fix so that only audio recordings are read as audio, and only images are read as images.

**Comment by nickdos** [comment]
This seems to be working as expected now. I suspect an issue on images.ala.org.au was the cause but has since been fixed... 

@TaniaGLaity, please confirm if this is good to close?

**Comment by TaniaGLaity** [comment]
@nickdos appears to be from a few examples tested - Emu and Pacific Black Duck
