### ISSUE TITLE
Species name as link not working for some species

### ISSUE THREAD

**Issue by Sherrin-ALA** [AtlasOfLivingAustralia/ala-bie-hub#75]
Camaercrista mimosoides is the accepted name for this species - https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2916908

However this link returns an error - https://bie.ala.org.au/species/Chamaecrista_mimosoides

The format works for other species in this genus - e.g https://bie.ala.org.au/species/Chamaecrista_symonii

**Comment by adam-collins** [comment]
This refers to the `linkIdentifier` field. It should be fixed by https://github.com/AtlasOfLivingAustralia/bie-index/issues/330

**Comment by timhicks-ala** [comment]
Reported by a user in https://support.ehelp.edu.au/a/tickets/192488

https://bie.ala.org.au/species/Alternanthera_nana causes an error
https://bie.ala.org.au/species/Alternanthera%20nana (or with a space) is fine

**Comment by adam-collins** [comment]
https://bie.ala.org.au/species/Alternanthera_nana is working now
