### ISSUE TITLE
'No images available for this taxon' appearing in species page gallery that have images

### ISSUE THREAD

**Issue by aliciadoddy** [AtlasOfLivingAustralia/ala-bie-hub#76]
Both in BIE test and in prod, even if a species page gallery tab has images available, a section is appearing - ' No images available for this taxon'.

![Image](https://user-images.githubusercontent.com/118698799/261885507-53aed951-e12c-4d5c-9707-7cb53997710d.PNG)

Test page
https://bie-test.ala.org.au/species/https://biodiversity.org.au/afd/taxa/2a4e373b-913a-4e2a-a53f-74828f6dae7e#gallery

More than one species page demonstrating issue
https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/2a4e373b-913a-4e2a-a53f-74828f6dae7e#gallery

https://bie.ala.org.au/species/https://id.biodiversity.org.au/taxon/apni/51382879#gallery

This text should not be displaying for species pages with images available.

**Comment by timhicks-ala** [comment]
Reported by a user via the helpdesk: https://support.ehelp.edu.au/a/tickets/183216

**Comment by adam-collins** [comment]
now fixed
