### ISSUE TITLE
Type specimen and regular specimen images not appearing in enlarged view in species page gallery

### ISSUE THREAD

**Issue by aliciadoddy** [AtlasOfLivingAustralia/ala-bie-hub#77]
See Type image and Specimen images for as example https://bie.ala.org.au/species/https://id.biodiversity.org.au/taxon/apni/51286863#gallery

Enlarged view produces blank view, won't load in -
![Image](https://user-images.githubusercontent.com/118698799/261923293-e230804a-5af4-4640-8f09-9f297929b7db.PNG)

This problem appears from a quick investigation to be specific to images from the data resource 'NSW AVH feed', although this will need verification. 

Images from other data resources seem to load in fine for the example BIE page, e.g., University of Melbourne AVH 

![Image](https://user-images.githubusercontent.com/118698799/261923583-b843720e-c582-4c64-bca7-8aed99d362ea.PNG)

Can this please be looked into, thanks :)

**Comment by adam-collins** [comment]
fixed in 3.1.1
