### ISSUE TITLE
Image available on overview page, but not in species page gallery

### ISSUE THREAD

**Issue by aliciadoddy** [AtlasOfLivingAustralia/ala-bie-hub#78]
There is an image available for this species, but for some reason it is only visible on the overview page.

https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/11554f83-006f-45f6-9011-bf6853f7b11f#overview

For the species page gallery tab, this image is not being displayed. It is unclear why this is, or whether this may be an issue for other species pages as well.

https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/11554f83-006f-45f6-9011-bf6853f7b11f#gallery

**Comment by adam-collins** [comment]
The difference is that `qualityProfile=ALA` is applied only when searching for gallery images, not front page images.

The fix is to apply `qualityProfile=ALA` to the front page images.

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/ala-bie-hub/pull/83

**Comment by adam-collins** [comment]
On second thought, the ALA data quality filter is not appropriate here. Using a consistent image filter instead.

Open to suggestions for change:
`fq=geospatial_kosher:true&fq=-user_assertions:50001&fq=-user_assertions:50005`
