### ISSUE TITLE
Sometimes images attached to records and available through the image app are not being pulled onto the BIE species pages.

### ISSUE THREAD

**Issue by aliciadoddy** [AtlasOfLivingAustralia/ala-bie-hub#79]
Generally speaking, specimen images are excellent quality and provide visual information about species that other photos, such as those provided by citizen scientists, do not. It would be beneficial to ensure that all these images that have been shared with ALA are visible on the species pages as well.

Currently, sometimes images attached to records and available through the image app are not being displayed on the BIE species pages. It is unclear why this is, but here is one example -

E.g., Uperoleia altissima
We can see there are multiple specimen images available, e.g., this occurrence record from QM

https://biocache.ala.org.au/occurrences/9e38ad0c-ec7d-4f54-8f64-fc65bc164922

Here is one of these images in the image app
https://images.ala.org.au/image/details?imageId=ff788704-42c8-4259-b60e-e5c004fb1f25

But these images do not display on the BIE species pages. (it appears only one does on the overview, but missing entirely from gallery)
https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/8be23c11-c4f9-41b6-8128-e8c654b31304#gallery

**Comment by adam-collins** [comment]
Adding multiple images per occurrence can be done. It will, however, highlight problems such as this https://biocache-test.ala.org.au/occurrences/831e1a10-e59a-403b-85ce-329a75c24e77, 2 identical, or near identical, images for one occurrence.

**Comment by adam-collins** [comment]
Included as part of pull request https://github.com/AtlasOfLivingAustralia/ala-bie-hub/pull/83

**Comment by TaniaGLaity** [comment]
@adam-collins does this mean this issue can be closed now?
