### ISSUE TITLE
More Issues as reported in #78 - images not in repository when clicked on

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/ala-bie-hub#80]
This has now been reported by three external users. Examples include:

https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2914824 - click on main image - doesn't work (say's there is nothing in the gallery)

https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2904037#overview - click on main image and is there but if you click on gallery there is nothing there

**Comment by javier-molina** [comment]
#78 is the main issue for this

**Comment by CamSlatyer** [comment]
LOL Isn't that why I gave it the heading: more issues as reported in #78, lol? :D

**Comment by javier-molina** [comment]
Agreed, but the title does not autolink as the comments do :-) If you are happy I can close this and add your comment to #78 so we keep the conversation in one place.

**Comment by CamSlatyer** [comment]
Absolutely – I was told to add in as a separate issue ! 😊

**Comment by adam-collins** [comment]
Clicking on the images in the BIE pages linked on both the overview and gallery tabs results in a popup containing the images. Closing as it is working.
