### ISSUE TITLE
Enable the same map layers as Biocache uses

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#82]
As a user I want to see the same layers in maps for both BIE and Biocache and I want to see the last one I selected as the default layer

**Requirement**

- Enable Minimal, Road, Terrain and Satellite
- Rename base layer to Minimal
- Display by default the last layer selected by a user

![Screenshot 2023-08-25 at 11 41 33 am](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/assets/8326394/cd3221ac-0b1d-4eec-8eb5-8839c3840d0f)
Biocache Layers

![Screenshot 2023-08-25 at 11 41 52 am](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/assets/8326394/d2738c92-7766-46d2-b024-25041b57d039)
BIE Layers

**Comment by TaniaGLaity** [comment]
contrary to advice from Icon Agency - new requirements in different issues now - closing this one
