### ISSUE TITLE
Content description improvements

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#85]
This issue is an extension for #42 

**Requirements**
Remove the content for External links keeping only the Taxon Identifiers section. 

See screenshot and sample pages 
![Image](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/assets/8326394/bfda4958-7d78-465e-bef6-c62abeb3f6d4)

- https://bie-test.ala.org.au/species/NZOR-6-24112#overview 
- https://bie-test.ala.org.au/species/https://biodiversity.org.au/afd/taxa/e6aff6af-ff36-4ad5-95f2-2dfdcca8caff 

**Rational**
Some pages will contain taxonomic information that may conflict with the information already provided by the ALA.

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/c41b0a2f356a21c6de897cc32ac324be4d5c1ec8

**Comment by kylie-m** [comment]
tested for Gallirallus philippensis, and Osphranter rufus, passed
