### ISSUE TITLE
Bie-hub v 3.1.0-SNAPSHOT issues – testing round 2

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/ala-bie-hub#86]
1. Images in test not loading (Known issue. Not a software bug, is a data issue in test not related to BIE)

2. Text wrap not functioning on occurrences button under map (Minor issue)

3. Hero image not pulling in to Fieldguide (Enhancement: logged in Fieldguide [#26](https://github.com/AtlasOfLivingAustralia/fieldguide/issues/26))

**Comment by adam-collins** [comment]
done
