### ISSUE TITLE
On search results page, "view images of species within this genus" link fails

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/ala-bie-hub#87]
This may be happening only for some taxa (reported as happening for genus and higher, not for species).

Example on BIE production: [search for Prepocosma genus](https://bie.ala.org.au/search?q=Prepocosma) - click the [View images of species within this genus](https://bie.ala.org.au/image-search/https%3A//biodiversity.org.au/afd/taxa/d10c2c15-8b36-4974-818b-1442ca67032e) link under the genus result - no images returned.  Click through to the [main genus taxon page](https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/d10c2c15-8b36-4974-818b-1442ca67032e), though, and there are images in the Gallery tab.

**Comment by matthewandrews** [comment]
Reported in ticket 185206.

**Comment by kylie-m** [comment]
I've tried this out too and am getting the same issue for every taxa I've tried –  10+ and ranging from kingdom to genus level – it does seem to be everything genus level and above as they all have that 'View images of species within this <taxa>' link

**Comment by matthewandrews** [comment]
(there is a workaround for users, which is to go to the actual taxon page e.g. the genus and go to the Gallery tab - this issue is to fix the link on the search results page)

**Comment by adam-collins** [comment]
This was just the api gateway config was missing OPTIONS handling on the service.
