### ISSUE TITLE
gallery image popups not working

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/ala-bie-hub#88]
error message shows that the imageId is unknown. Fixed in commit https://github.com/AtlasOfLivingAustralia/ala-bie-hub/commit/139aa0002489511df8e4f0b680ac49bc2cd55bc0

**Comment by kylie-m** [comment]
Relates to user support tickets:
https://support.ehelp.edu.au/a/tickets/185995
https://support.ehelp.edu.au/a/tickets/185997
