### ISSUE TITLE
Add additional language check to Encyclopedia of Life (EOL) API's content description.

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/ala-bie-hub#9]
Currently some objects returned  from EOL to be displayed in the BIE species page  are incorrectly tagged as english `en` for the `language` metadata attribute. This results in the BIE species page displaying content for species in a non-english language.   

![Screen Shot 2022-07-18 at 7 24 47 pm](https://user-images.githubusercontent.com/105408469/179482501-1be97b05-6a58-4c71-adfa-16bcc3cb0aba.png)

![Screen Shot 2022-07-14 at 1 59 20 pm](https://user-images.githubusercontent.com/105408469/179480981-8dfb5ebf-36c7-49fd-bcb2-67f33c37ef76.png)

--SHORT TERM FIX--
Add additional language check to EOL content description to prevent  results in languages other than specified i.e. English. 

Further info [here](https://confluence.csiro.au/pages/viewpage.action?pageId=1666713368).

**Comment by sughics** [comment]
### ISSUE
Initial solution was unable  to filter out some non-english content. e.g. Some content in Korean were still being displayed. 

It was caused due to the standard behaviour of Apache tika langauge detector when detecting languages in mixed language content. e.g. 
 - When a text content is mostly in  Korean with small about of  English  e.g. references, it can be detected as English. 
 
On closer inspection, this appears to be occurring  due to  detector having a higher confidence in the English than Korean and returning  the language with  he higher confidence value.  
 
### FIX
1.  Split the text content into multiple segments.
2. Detect language for individual segments and store the detected language in a list. 
3. Count the list and determine the language with the highest occurrence in the content.

**Comment by sughics** [comment]
The attached files includes links for species that  were tested for language issues after the above fix.
[Species page diff language_v2.xlsx](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/files/9177904/Species.page.diff.language_v2.xlsx)

**Comment by yasima-csiro** [comment]
Sanity test
[Bie sanity testing.xlsx](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/files/9177922/Bie.sanity.testing.xlsx)
