### ISSUE TITLE
"View images of species within this [genus|family|etc]" feature in BIE does not show images

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/ala-bie-hub#90]
Reported in https://support.ehelp.edu.au/a/tickets/186881

Examples:
https://bie.ala.org.au/search?q=VITACEAE
https://bie.ala.org.au/search?q=osphranter+rufus (second result down)

In each case, the "View images of species within this (group)" link goes to a new page that endlessly tries to display images, but never does.

![images of vitaceae](https://github.com/AtlasOfLivingAustralia/ala-bie-hub/assets/57081387/58cd70e1-699b-4d30-99a3-68eb13805876)

**Comment by adam-collins** [comment]
Fixed. A gateway service definition was incomplete.
