### ISSUE TITLE
Records with assertions should not be selected for species hero images

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/ala-bie-hub#93]
A recurring support request is where the hero image for a species belongs to a record with a user assertion for an incorrect identification - meaning the representative image for a species page in BIE is of the wrong species.

We can manually set hero images, however this is a manual process and relies on users notifying us in some way in addition to the user assertion being raised.

BIE should be able to reject hero images from occurrences where the species identification is in doubt, as an automatic data quality process.

Additionally, some sort of admin notification for when this happens would allow us to proactively select ideal replacement hero images in cases like this.

**Comment by TaniaGLaity** [comment]
partially fixed - admins now have the ability to hide images - however, no notification if a record is flagged that includes an image

**Comment by TaniaGLaity** [comment]
duplicate of issue https://github.com/AtlasOfLivingAustralia/ux-ui/issues/273
